# Generated by Django 2.1.2 on 2018-11-02 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evt_name', models.CharField(max_length=200)),
                ('reporter_name', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('add_desc', models.CharField(max_length=100)),
                ('emergency_type', models.CharField(choices=[('AMB', 'Ambulance'), ('EVAC', 'Rescue and Evacuation'), ('FIRE', 'Firefighting'), ('GAS', 'Gas leak control')], default='AMB', max_length=4)),
            ],
        ),
    ]
