# Generated by Django 2.0.6 on 2018-11-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181106_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.CharField(default='0000000', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.CharField(default='0000000', editable=False, max_length=100),
        ),
    ]
