# Generated by Django 2.1.2 on 2018-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20181106_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.CharField(default='0', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.CharField(default='0', editable=False, max_length=100),
        ),
    ]
