# Generated by Django 2.1.2 on 2018-11-11 16:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20181106_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='longitude',
            new_name='long',
        ),
        migrations.RemoveField(
            model_name='event',
            name='emergency_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='evt_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reporter_name',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='assist_type',
            field=models.CharField(choices=[('A', 'Emergency Ambulance'), ('B', 'Rescue and Evacuation'), ('C', 'Fire-Fighting'), ('D', 'Gas Leak Control')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('\\b[6,8,9]\\d{7}\\b$')]),
        ),
        migrations.AddField(
            model_name='event',
            name='reporter_first',
            field=models.CharField(default='First Name', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='reporter_last',
            field=models.CharField(default='Last Name', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default=event.models.create_title, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='add_desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='postal_code',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator('\\b\\d{6}\\b$')]),
        ),
    ]
