# Generated by Django 2.1.2 on 2018-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20181112_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assist_type',
            field=models.CharField(choices=[('A', 'Emergency Ambulance'), ('B', 'Rescue and Evacuation'), ('C', 'Fire-Fighting'), ('D', 'Gas Leak Control')], max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='reporter_first',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='reporter_last',
            field=models.CharField(max_length=30),
        ),
    ]
