# Generated by Django 2.1.2 on 2018-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=10)),
                ('incident_time', models.DateTimeField(auto_now_add=True)),
                ('incident_postal_code', models.IntegerField(max_length=6)),
                ('incident_id', models.IntegerField(max_length=10)),
                ('incident_response', models.BooleanField(default=False)),
                ('incident_reported_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=50)),
                ('operator_id', models.IntegerField(verbose_name=10)),
                ('operator_phone', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PMOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prime_minister_office_name', models.CharField(max_length=50)),
                ('prime_minister_office_id', models.IntegerField(max_length=10)),
                ('prime_minister_office_phone', models.IntegerField(max_length=8)),
                ('prime_minister_office_email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=50)),
                ('shelter_description', models.CharField(max_length=250)),
                ('shelter_address', models.CharField(max_length=70)),
                ('shelter_postal_code', models.IntegerField(max_length=6)),
                ('shelter_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Taskforce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskforce_name', models.CharField(max_length=50)),
                ('taskforce_id', models.IntegerField(max_length=10)),
                ('taskforce_phone', models.IntegerField(max_length=8)),
            ],
        ),
    ]
