# Generated by Django 2.1.2 on 2018-10-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0002_incident_operator_pmoffice_shelter_taskforce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_postal_code',
            field=models.IntegerField(verbose_name=6),
        ),
        migrations.AlterField(
            model_name='pmoffice',
            name='prime_minister_office_id',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='pmoffice',
            name='prime_minister_office_phone',
            field=models.IntegerField(verbose_name=8),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='shelter_id',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='shelter_postal_code',
            field=models.IntegerField(verbose_name=6),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='taskforce_id',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
