# Generated by Django 2.1.2 on 2018-10-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0003_auto_20181024_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operator_phone',
            field=models.IntegerField(verbose_name=8),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='taskforce_phone',
            field=models.IntegerField(verbose_name=8),
        ),
    ]
