# Generated by Django 2.1.2 on 2018-10-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0004_auto_20181024_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='id',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pmoffice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='taskforce',
            name='id',
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='pmoffice',
            name='prime_minister_office_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='shelter_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='taskforce_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=10),
        ),
    ]
