# Generated by Django 2.1.2 on 2018-10-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0005_auto_20181024_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskforce',
            name='taskforce_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Taskforce ID'),
        ),
    ]
