# Generated by Django 2.1.2 on 2018-10-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0007_auto_20181024_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
