# Generated by Django 2.1.2 on 2018-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0009_auto_20181024_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmoffice',
            name='prime_minister_office_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Prime minister office ID'),
        ),
        migrations.AlterField(
            model_name='pmoffice',
            name='prime_minister_office_phone',
            field=models.IntegerField(verbose_name='Prime minister office Phone'),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='taskforce_phone',
            field=models.IntegerField(verbose_name='Taskforce phone'),
        ),
    ]
