# Generated by Django 2.1.2 on 2018-10-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0010_auto_20181024_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Incident Time'),
        ),
    ]
