# Generated by Django 2.1.2 on 2018-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMO', '0011_auto_20181024_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
